---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
        - cluster: engineering-dev
          url: https://1.2.3.4
  template:
    metadata:
      name: nginx
    spec:
      project: addons
      sources:
        - repoURL: 'https://github.com/danielloader/nginx-k8s'
          targetRevision: 'HEAD'
          ref: values
        - chart: 'nginx'
          repoURL: 'https://github.com/danielloader/nginx-k8s'
          targetRevision: 'HEAD'
          path: charts
          helm:
            releaseName: 'nginx'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/values/default.yaml
            valuesObject: {}
      destination:
        namespace: 'nginx'
        name: 'default'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.