---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
        - cluster: engineering-dev
          url: https://1.2.3.4
  template:
    metadata:
      name: nginx
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielloader/nginx-k8s.git'
        targetRevision: 'HEAD'
        path: charts/nginx
        helm:
          releaseName: 'nginx'
          ignoreMissingValueFiles: true
          valueFiles:
            - $values/values/default.yaml
          valuesObject: {}
      destination:
        namespace: 'nginx'
        name: 'in-cluster'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.