---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
        - cluster: local-dev
  template:
    metadata:
      name: nginx
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/danielloader/nginx-k8s.git'
          targetRevision: 'HEAD'
          ref: values
        - repoURL: 'https://github.com/danielloader/nginx-k8s.git'
          targetRevision: 'HEAD'
          path: charts/nginx
          helm:
            releaseName: 'nginx'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/values/default.yaml
            valuesObject:
              podAnnotations: 
                test: value2 # overrides value in values/default.yaml
      destination:
        namespace: 'nginx'
        name: 'in-cluster'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.