---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
        - cluster: local-dev
  template:
    metadata:
      name: nginx
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danielloader/nginx-k8s.git'
        targetRevision: 'HEAD'
        path: charts/nginx
        helm:
          releaseName: 'nginx'
          ignoreMissingValueFiles: false
          valueFiles:
            - values/default.yaml
          valuesObject:
            podAnnotations: 
              test: value # overrides value in values/default.yaml
              clusterFromObject: '{{.cluster}}' # check templating works at all
      destination:
        namespace: 'nginx'
        name: 'in-cluster'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.